on:
  schedule:
    - cron: '0 12 * * *'
  pull_request:
  workflow_dispatch:    
name: Update Discovery Generated Types
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 16
      # Install all deps, including dev dependencies.
      - run: npm install
      # Generate types
      - run: npm run types
      # Submit pull request
      - run: npm run submit-discovery-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
