on:
  schedule:
    - cron: '0 12 * * TUE'
  workflow_dispatch:
name: Update Discovery Generated Types
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 24
      # Install all deps, including dev dependencies.
      - run: npm install
      # Generate types
      - run: npm run types
      # Install samples deps
      - run: cd samples/ && npm install && cd ../
      # Fix formatting
      - run: npm run fix
      # Submit pull request
      - uses: googleapis/code-suggester@v5
        env:
          ACCESS_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
        with:
          command: pr
          upstream_owner: googleapis
          upstream_repo: nodejs-bigquery
          description: 'Automated pull-request to keep BigQuery Discovery types up-to-date.'
          title: 'chore: update types from Discovery'
          message: 'chore: update types from Discovery'
          branch: update-discovery-patch
          git_dir: '.'
          fork: true
          force: true
